export const ADD_THIS_YEAR_MOVIES='ADD_THIS_YEAR_MOVIES';

export const ADD_IMDB_ID_MOVIES='ADD_IMDB_ID_MOVIES';

export const ADD_NEW_MOVIES='ADD_NEW_MOVIES';

export const ADD_POPULAR_MOVIES_WITH_IMDB='ADD_POPULAR_MOVIES_WITH_IMDB';

export const ADD_POPULAR_MOVIES='ADD_POPULAR_MOVIES';

export const ADD_NEW_MOVIES_IMDB_20='ADD_NEW_MOVIES_IMDB_20';

export const ADD_NEW_MOVIES_20='ADD_NEW_MOVIES_20';

export const ADD_POPULAR_MOVIES_IMDB_20='ADD_POPULAR_MOVIES_IMDB_20';

export const ADD_POPULAR_MOVIES_20='ADD_POPULAR_MOVIES_20';

export const ADD_NOW_SERIES_ONLY_IMDB_10='ADD_NOW_SERIES_ONLY_IMDB_10';

export const ADD_NOW_SERIES_10='ADD_NOW_SERIES_10';

export const ADD_NOW_SERIES_20='ADD_NOW_SERIES_20';

export const ADD_POPULAR_SERIES_ONLY_IMDB_10='ADD_POPULAR_SERIES_ONLY_IMDB_10';

export const ADD_POPULAR_SERIES_10='ADD_POPULAR_SERIES_10';

export const ADD_POPULAR_SERIES_20='ADD_POPULAR_SERIES_20';

export const ADD_MOVIE_CAST_IMDB_ID='ADD_MOVIE_CAST_IMDB_ID';

export const MOVIE_CAST_ARRAY='MOVIE_CAST_ARRAY';

export const LIKED='LIKED';

export const REMOVE_LIKE='REMOVE_LIKE';

export const FAVORITE='FAVORITE';

export const REMOVE_FAVORITE='REMOVE_FAVORITE';

export const GENRE_ARRAY='GENRE_ARRAY';

export const ADD_GENRE='ADD_GENRE';

export const PROFILE_IMAGE='PROFILE_IMAGE';

export const CACHE='CACHE';